### ISSUE TITLE
Order was claimed and done by 2 chefs

### ISSUE THREAD

**Issue by ImRodry** [CookieBilly/DessertShop#4]
The order with the ID 242337 requested by Billy was claimed by 2 chefs: myself and Harvey. Since I was the last one to claim it, the bot classified the order as mine bur we were both still able to send the pic and we did. I don’t think this broke anything but it is not the first time 2 chefs get the same order so please fix this (here is a quick video of the chat when it happened https://youtu.be/troBIwmH5a0)

**Comment by BillyDotWS** [comment]
No current way to prevent 2 people at once from claiming it, just try and give it a few seconds before rushing in and claiming the order.
