### ISSUE TITLE
Chefs have <none> after being tipped

### ISSUE THREAD

**Issue by ImRodry** [CookieBilly/DessertShop#5]
In the channel #chef-tipping it says that chefs have <none> money after being tipped (this happens on every tip not just one specifically)

**Comment by BillyDotWS** [comment]
Unsure what you mean?
![image](https://user-images.githubusercontent.com/41408185/44679659-7f43bd80-aa33-11e8-9217-90f6ea0a6c9f.png)

**Comment by ImRodry** [comment]
I'm sorry, check #currency-logs

**Comment by ImRodry** [comment]
Here is an example 
![image](https://user-images.githubusercontent.com/38259440/44684280-96d57300-aa40-11e8-97ba-c8c4cf2bc070.png)

**Comment by BillyDotWS** [comment]
Just a misplaced % in https://github.com/CookieBilly/DessertShop/blob/master/code/main.sk

Sorted.
