### ISSUE TITLE
Daily command still exists even though you now get your daily reward automatically in your bank

### ISSUE THREAD

**Issue by ImRodry** [CookieBilly/DessertShop#7]
So when you vote you get a PM from the bot telling you to do `@Dessert Shop daily` to claim you reward even though there's no need to do this anymore so I suggest you change the message to "Your 20 dollars have been added to your global bank. In order to transfer them to a specific server do @Dessert Shop bank withdraw 20"

**Comment by BillyDotWS** [comment]
Fixed
