### ISSUE TITLE
Order by <none> that can't be claimed

### ISSUE THREAD

**Issue by ImRodry** [CookieBilly/DessertShop#9]
The order #940462 with the request "disappointing cake" can not be claimed and when I did @Dessert Shop orderinfo it said that it was ordered by <none>#<none> in guild <none> (448566083025109012)

**Comment by ImRodry** [comment]
Also I could reject the order but not accept it
![image](https://user-images.githubusercontent.com/38259440/45021862-99306200-b02a-11e8-9749-afe433c3c4ff.png)
![image](https://user-images.githubusercontent.com/38259440/45021910-b9602100-b02a-11e8-991a-04d7160a3bba.png)
P.S. I had to reject the order since it was bugged and there was nothing I could do so please remove that guy's warning

**Comment by ImRodry** [comment]
Same thing happened with order 790326...

**Comment by BillyDotWS** [comment]
If the bot is kicked from a guild, it can't be claimed.
